2020-01-28 09:43:00,199 ERROR: Exception on /reset_password_request [POST] [in /Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Pleachy/microblog/app/routes.py", line 311, in reset_password_request
    send_password_reset_email(user)
  File "/Users/Pleachy/microblog/app/email.py", line 29, in send_password_reset_email
    user=user, token=token))
  File "/Users/Pleachy/microblog/app/email.py", line 17, in send_email
    mail.send(msg)
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
2020-01-28 09:43:29,899 INFO: Microblog startup [in /Users/Pleachy/microblog/app/__init__.py:75
2020-01-28 09:43:38,876 ERROR: Exception on /reset_password_request [POST] [in /Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Pleachy/microblog/app/routes.py", line 311, in reset_password_request
    send_password_reset_email(user)
  File "/Users/Pleachy/microblog/app/email.py", line 29, in send_password_reset_email
    user=user, token=token))
  File "/Users/Pleachy/microblog/app/email.py", line 17, in send_email
    mail.send(msg)
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
2020-01-28 10:02:41,017 INFO: Microblog startup [in /Users/Pleachy/microblog/app/__init__.py:75
2020-01-28 10:02:46,128 ERROR: Exception on /reset_password_request [POST] [in /Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891
Traceback (most recent call last):
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Pleachy/microblog/app/routes.py", line 311, in reset_password_request
    send_password_reset_email(user)
  File "/Users/Pleachy/microblog/app/email.py", line 29, in send_password_reset_email
    user=user, token=token))
  File "/Users/Pleachy/microblog/app/email.py", line 17, in send_email
    mail.send(msg)
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/Users/Pleachy/microblog/venv/lib/python3.7/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
2020-01-28 10:04:01,089 INFO: Microblog startup [in /Users/Pleachy/microblog/app/__init__.py:75
2020-01-28 10:16:40,519 INFO: Microblog startup [in /Users/Pleachy/microblog/app/__init__.py:75
2020-01-28 10:27:38,102 INFO: Microblog startup [in /Users/Pleachy/microblog/app/__init__.py:75
2020-01-28 10:30:42,651 INFO: Microblog startup [in /Users/Pleachy/microblog/app/__init__.py:75
2020-01-28 10:31:34,816 INFO: Microblog startup [in /Users/Pleachy/microblog/app/__init__.py:75
2020-01-28 10:42:35,892 INFO: Microblog startup [in /Users/Pleachy/microblog/app/__init__.py:75
